title: Doctored
description: "A  blog theme prioritizing uniqueness, complexity, and minimalism."
github: "https://github.com/joshpinto6/doctored"
encoding: utf-8

plugins:
  - jekyll-postcss
  - jekyll-git_metadata
  - kramdown-parser-gfm

exclude: 
- README.md
- LICENSE
- "*.gem"
- "*.gemspec"
- vendor
- Gemfile.lock
- .gitignore
- bin
- node_modules
- package-lock.json
- postcss.config.js

sass:
  sourcemap: never

postcss:
  cache: false

keep_files:
  - assets/css/tailwind.css
  - assetss/css/tailwind.css.map
  - assets/js
