title: Doctored
description: "A  blog theme prioritizing uniqueness, complexity, and sophistication."
github: "https://github.com/joshpinto6/doctored"
url: "https://joshpinto6.github.io/doctored"
encoding: utf-8

plugins:
  - jekyll-postcss
  - jekyll-git_metadata
  - kramdown-parser-gfm
  - jekyll-gfm-admonitions
  - jekyll-sitemap
  - jekyll-feed

feed:
  icon: /assets/images/favicon.png

redcarpet:
  extensions: ["with_toc_data"]

collections:
  projects:
    output: true

exclude: 
- README.md
- LICENSE
- "*.gem"
- "*.gemspec"
- vendor
- Gemfile.lock
- .gitignore
- bin
- node_modules
- package-lock.json
- postcss.config.js

sass:
  sourcemap: never

postcss:
  cache: false

keep_files:
  - assets/css/tailwind.css
  - assetss/css/tailwind.css.map
  - assets/js
